### ISSUE TITLE
Why isn't the StructureComparer class static?

### ISSUE THREAD

**Issue by thiagofm** [jeduardocosta/structure-comparer#3]
It might be a good idea to make it static. Looking at the tests and the codebase, the class is always initialized with empty args.

That way, it becomes a bit easier to use it(just a one-liner).

Cheers :P

**Comment by jeduardocosta** [comment]
I think it makes sense. This library should be used in unit testing projects. Thus, there will not be IoC's problems or other concerns due to the use of a static class. 

I'll make that change and see how it looks.

Thanks.

**Comment by jeduardocosta** [comment]
Done https://github.com/jeduardocosta/StructureComparer/commit/8086453eabbc074b05b23613aa7b5ec93bfdf5e0
